---
- name: cloning repo
  git:
    repo: "{{ github_repo }}"
    version: "{{ github_branch | default('deploy-ansible') }}"
    dest: "{{ dest_dir }}"
    clone: yes
    update: yes

- name: docker-compose app
  docker-compose:
    project_src: {{ docker-dir }}
    files:
      - docker-compose.yml
